baseURL = "https://www.replicante.io/"
disableKinds = ["taxonomyTerm", "sitemap"]
languageCode = "en-gb"
publishDir = "dist"
theme = "replicante"
title = "Replicante"


[blackfriday]
hrefTargetBlank = true
